<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxhxFuv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxhxFuv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxhxFuv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxhxFuv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxhxFuv\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxhxFuv',
    'container.build_id' => '15cd8bd1',
    'container.build_time' => 1680526859,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxhxFuv');
